
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-18T11:23:13-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "06f0eb069b1569f100ebefa3739f28bc1adea2d4",
 "version": "0+untagged.19.g06f0eb0.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
